site_name: Dhall Kubernetes
repo_url: https://github.com/dhall-lang/dhall-kubernetes
strict: false
theme:
  name: null
  custom_dir: theme
nav:
  - Overview: index.md
  - User Guide:
      - Introduction: intro.md
      - Apply: apply.md
      - Secrets and ConfigMaps: config.md
      - Container Images: images.md
  - Projects using Dhall: projects.md
