site_name: Dhall Kubernetes
repo_url: https://github.com/dhall-lang/dhall-kubernetes
strict: false
theme:
  name: null
  custom_dir: theme
nav:
  - Overview: index.md
  # - Tutorial:
  #     - Step 1:
  #     - Step 2:
  #    
